name: 'Action Should Deploy'
description: 'Prevent deployments when the commit SHA and deployment SHA is the same'
author: 'Mario Silva @ Utrust'
inputs:
  token:
    required: true
  sha:
    required: false
  environment:
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
